/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carritodecompras.servidor;

import carritodecompras.productos.DialogoPaqueteria;
import ImagenesInterfaz.PanelFondo;
import ImagenesInterfaz.UIFunctions;
import carritodecompras.productos.DialogoCategoria;
import carritodecompras.productos.GestorDeDatos;
import carritodecompras.productos.Operacion;
import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * @author miguel
 */
public class OpcionesServidor extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form OpcionesServidor
     */
    private int x;
    private int y;
    private final PanelFondo contenedor = new PanelFondo("/ImagenesInterfaz/fondo.png");

    public OpcionesServidor() {
        
        setContentPane(contenedor);
        this.setUndecorated(true);//Elimina los bordes de la ventana
        initComponents();
        init();
        this.setResizable(false);//no permite que sea redimincionable
        this.setLocationRelativeTo(this);//la ventana aparece al centro de la pantalla
        AWTUtilities.setWindowOpaque(this, false);// Genera transparencia
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ImagenesInterfaz/Icono.png"));
        setIconImage(icon);
        this.setTitle("CML EXPRESS"); 
        setVisible(true);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        Minimize = new javax.swing.JButton();
        Categoria = new javax.swing.JButton();
        Productos = new javax.swing.JButton();
        Paqueterias = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(46, 254, 89));

        Close.setText("X");

        Minimize.setText("_");

        Categoria.setBackground(new java.awt.Color(30, 138, 254));
        Categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/categoria.png"))); // NOI18N
        Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaActionPerformed(evt);
            }
        });

        Productos.setBackground(new java.awt.Color(15, 187, 45));
        Productos.setForeground(new java.awt.Color(2, 170, 220));
        Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/ProductosCategorias.png"))); // NOI18N

        Paqueterias.setBackground(new java.awt.Color(255, 245, 0));
        Paqueterias.setForeground(new java.awt.Color(160, 144, 5));
        Paqueterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/Paqueterias.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(Paqueterias)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Productos)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Minimize)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Close)
                    .addComponent(Minimize))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Productos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(Paqueterias)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesServidor().setVisible(true);
            }
        });
        
        ObjectOutputStream oos = null;
        ObjectInputStream ois = null;

        try {
            ServerSocket s = new ServerSocket(9999);
            System.out.print("Servidor iniciado...\n");
            GestorDeDatos gdd = GestorDeDatos.getInstance();
            
            for (;;) {
                Socket cl = s.accept();
                System.out.print("Cliente conectado desde "
                        + cl.getInetAddress() + ":" + cl.getPort() + "\n");
                oos = new ObjectOutputStream(cl.getOutputStream());
                ois = new ObjectInputStream(cl.getInputStream());
                boolean seguir = true;
                while(seguir)
                {
                    Operacion op = (Operacion) ois.readObject();
                    seguir = gdd.ejecutarOperacion(oos, op, ois);
                }
                    
                
                
                /**
                 * El GestorDeDatos es el encargado de recibir la operacion
                 * ejecutarla y devolver lo solicitado
                 */
                

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource().equals(this.Close))
        {
            UIFunctions.closeWindow();    
        }
        else if(ae.getSource().equals(this.Minimize))
        {
            UIFunctions.minimizeWindow(this);
        }
        else if(ae.getSource().equals(this.Paqueterias))
        {
            DialogoPaqueteria dialog = null;
            try {
                dialog = new DialogoPaqueteria(new javax.swing.JFrame(), true);
            } catch (IOException ex) {
                Logger.getLogger(OpcionesServidor.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(OpcionesServidor.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
            dialog.setVisible(true);
        }
        
        else if(ae.getSource().equals(this.Categoria)){
            System.out.println("\nSeleccionaste Categorias\n");
            DialogoCategoria dialog = null;
            try {
                dialog = new DialogoCategoria(new javax.swing.JFrame(), true);
            } catch (IOException ex) {
                Logger.getLogger(OpcionesServidor.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(OpcionesServidor.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
            dialog.setVisible(true);
        }
        /**
         * Agrega tus else if del boton productos  y sus JDialog
         */
    }
    
     private void init()
     {
        this.Close.addActionListener(this);
        this.Minimize.addActionListener(this);
        this.Paqueterias.addActionListener(this);
        this.Categoria.addActionListener(this);
        this.Productos.addActionListener(this);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
     }

    private void formMousePressed(java.awt.event.MouseEvent evt) {                                  
        x=evt.getX();
        y=evt.getY();
        
    }                                 

    private void formMouseDragged(java.awt.event.MouseEvent evt) {                                  
        this.setLocation(this.getLocation().x+evt.getX()-x, this.getLocation().y+evt.getY()-y);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Categoria;
    private javax.swing.JButton Close;
    private javax.swing.JButton Minimize;
    private javax.swing.JButton Paqueterias;
    private javax.swing.JButton Productos;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
